# Generated by Django 4.2.28 on 2026-02-26 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='biryani_variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='biryani/images')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('types', models.CharField(choices=[('Hyderabadi', 'Hyderabadi'), ('Lucknowi', 'Lucknowi'), ('Kolkata', 'Kolkata'), ('Ambur', 'Ambur'), ('Dindigul', 'Dindigul')], max_length=20)),
            ],
        ),
    ]
