# Generated by Django 4.2.28 on 2026-02-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biryani', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biryani_variety',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='biryani_variety',
            name='types',
            field=models.CharField(choices=[('Hybd', 'Hyderabadi'), ('Luck', 'Lucknowi'), ('Kol', 'Kolkata'), ('Amb', 'Ambur'), ('Din', 'Dindigul')], max_length=20),
        ),
    ]
