# Generated by Django 4.2.28 on 2026-03-02 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biryani', '0002_biryani_variety_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('biryani', models.ManyToManyField(related_name='stores', to='biryani.biryani_variety')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(default='')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('biryani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='biryani.biryani_variety')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Biryani_Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100)),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(default=django.utils.timezone.now)),
                ('biryani', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='biryani.biryani_variety')),
            ],
        ),
    ]
